plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

title: "Maryana.Design"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images/projects/1"
    values:
      project: 1
  - scope:
      path: "assets/images/projects/2"
    values:
      project: 2
  - scope:
      path: "assets/images/projects/3"
    values:
      project: 3
  - scope:
      path: "assets/images/projects/4"
    values:
      project: 4
