title: "Maryana.Interior.Design"
url: "https://www.maryana.design"
author:
  name: "Maryana Kotova"
  email: "mail@maryana.design"
social:
  name: Maryana Interior Design
  links:
    - https://instagram.com/maryana.interior.design
    - https://web.facebook.com/maryana.interior.design
loc: Phuket
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
collections:
  pages:
    output: true
  portfolio:
    output: true
defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images/projects/1"
    values:
      project: 1
  - scope:
      path: "assets/images/projects/2"
    values:
      project: 2
  - scope:
      path: "assets/images/projects/3"
    values:
      project: 3
  - scope:
      path: "assets/images/projects/4"
    values:
      project: 4
  - scope:
      path: "assets/images/projects/5"
    values:
      project: 5
  - scope:
      path: "assets/images/projects/6"
    values:
      project: 6
  - scope:
      path: "assets/images/projects/7"
    values:
      project: 7
  - scope:
      path: "assets/images/projects/8"
    values:
      project: 8
  - scope:
      path: "assets/images/projects/9"
    values:
      project: 9
  - scope:
      path: "assets/images/projects/10"
    values:
      project: 10
  - scope:
      path: "assets/images/projects/11"
    values:
      project: 11
  - scope:
      path: "assets/images/projects/12"
    values:
      project: 12
  - scope:
      path: "assets/images/projects/13"
    values:
      project: 13
  - scope:
      path: "assets/images/projects/14"
    values:
      project: 14
  - scope:
      path: "assets/images/projects/15"
    values:
      project: 15
  - scope:
      path: "assets/images/projects/16"
    values:
      project: 16
  - scope:
      path: "assets/images/projects/17"
    values:
      project: 17
  - scope:
      path: "assets/images/projects/18"
    values:
      project: 18
  - scope:
      path: "assets/images/projects/19"
    values:
      project: 19
  - scope:
      path: "assets/images/projects/20"
    values:
      project: 20
  - scope:
      path: "assets/images/projects/21"
    values:
      project: 21
  - scope:
      path: "assets/images/projects/22"
    values:
      project: 22
  - scope:
      path: "assets/images/projects/23"
    values:
      project: 23
  - scope:
      path: "assets/images/projects/24"
    values:
      project: 24
  - scope:
      path: "assets/images/projects/25"
    values:
      project: 25
  - scope:
      path: "assets/images/projects/26"
    values:
      project: 26
  - scope:
      path: "assets/images/projects/27"
    values:
      project: 27   
  - scope:
      path: "assets/images/projects/28"
    values:
      project: 28
  - scope:
      path: "assets/images/projects/29"
    values:
      project: 29
  - scope:
      path: "assets/images/projects/30"
    values:
      project: 30      
  - scope:
      path: "assets/images/projects/31"
    values:
      project: 31
languages:
  - code: en
    slug: ""
    name: Eng
  - code: ru
    slug: /ru
    name: Рус
  - code: th
    slug: /th
    name: ไทย
feed:
  collections:
    portfolio:
      categories:
        - en
        - ru
        - th
pagination:
  enabled: true
  debug: false
  per_page: 6
